In [151]:
import pandas as pd

report = pd.read_csv('report.csv')
report.head()

,Sr.No,Fund,Implementing Organization Name,Health Post / Clinic,State,Township,Village Tract,Place,Type of place \n(Camp/Village/Ward),Name of Medical Person,...,Refered or Not,Referral Date,Cause of referral,Name of Referred Place,Type of Referred Facility,Follow-up Date,Teleconsultation,Remarks,referral,PEP
0,1,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
1,2,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
2,3,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
3,4,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
4,5,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!

In [152]:
list(report.columns)

['Sr.No',
 'Fund',
 'Implementing Organization Name',
 'Health Post / Clinic',
 'State',
 'Township',
 'Village Tract',
 'Place',
 'Type of place \n(Camp/Village/Ward)',
 'Name of Medical Person',
 'Date of Consultation\n(mm/dd/yy)',
 'Register No.',
 'Register.Code',
 'New/\nFollow up',
 'Name of patient ',
 'Age_yr',
 'Age_mth',
 'Age_day',
 'Age_Group',
 'Sex',
 'Address \n(if not the same with\nMoblile Clinic location)',
 'Father Name',
 'Diagnosis',
 'Sub_Category',
 'Category',
 'Consultation Type',
 'Treatment',
 'eligible to receive PEP?',
 'Receive PEP within 72 hours',
 'Disability',
 'Refered or Not',
 'Referral Date',
 'Cause of referral',
 'Name of Referred Place',
 'Type of Referred Facility',
 'Follow-up Date',
 'Teleconsultation',
 'Remarks',
 'referral',
 'PEP']

# Two type of data sturcture (Series , Dataframe)

In [61]:
type(report)

pandas.core.frame.DataFrame

In [21]:
report.index

RangeIndex(start=0, stop=908, step=1)

In [62]:
report["Name of patient "]

0        Daw Khin Hla
1        Daw Khin Yee
2          Daw Mya Aye
3        Daw Nu Nu Yee
4      Daw Kyu Kyu San
            ...
903                NaN
904                NaN
905                NaN
906                NaN
907                NaN
Name: Name of patient , Length: 908, dtype: object

In [153]:
pd.isna(report["Name of patient "])

0      False
1      False
2      False
3      False
4      False
       ...
903     True
904     True
905     True
906     True
907     True
Name: Name of patient , Length: 908, dtype: bool

In [63]:
pd.notna(report["Name of patient "])

0       True
1       True
2       True
3       True
4       True
       ...
903    False
904    False
905    False
906    False
907    False
Name: Name of patient , Length: 908, dtype: bool

In [95]:
report = pd.DataFrame(report)

In [5]:
report

,Sr.No,Fund,Implementing Organization Name,Health Post / Clinic,State,Township,Village Tract,Place,Type of place \n(Camp/Village/Ward),Name of Medical Person,...,Refered or Not,Referral Date,Cause of referral,Name of Referred Place,Type of Referred Facility,Follow-up Date,Teleconsultation,Remarks,referral,PEP
0,1,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
1,2,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
2,3,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
3,4,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
4,5,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,904,BHA,Shining Star,Mobile Clinic,Mandalay,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
904,905,BHA,Shining Star,Mobile Clinic,Mandalay,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
905,906,BHA,Shining Star,Mobile Clinic,Mandalay,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
906,907,BHA,Shining Star,Mobile Clinic,Mandalay,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
907,908,BHA,Shining Star,Mobile Clinic,Mandalay,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
report.head()

,Sr.No,Fund,Implementing Organization Name,Health Post / Clinic,State,Township,Village Tract,Place,Type of place \n(Camp/Village/Ward),Name of Medical Person,...,Refered or Not,Referral Date,Cause of referral,Name of Referred Place,Type of Referred Facility,Follow-up Date,Teleconsultation,Remarks,referral,PEP
0,1,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
1,2,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
2,3,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
3,4,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!
4,5,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!

In [154]:
report.columns

Index(['Sr.No', 'Fund', 'Implementing Organization Name',
       'Health Post / Clinic', 'State', 'Township', 'Village Tract', 'Place',
       'Type of place \n(Camp/Village/Ward)', 'Name of Medical Person',
       'Date of Consultation\n(mm/dd/yy)', 'Register No.', 'Register.Code',
       'New/\nFollow up', 'Name of patient ', 'Age_yr', 'Age_mth', 'Age_day',
       'Age_Group', 'Sex',
       'Address \n(if not the same with\nMoblile Clinic location)',
       'Father Name', 'Diagnosis', 'Sub_Category', 'Category',
       'Consultation Type', 'Treatment', 'eligible to receive PEP?',
       'Receive PEP within 72 hours', 'Disability', 'Refered or Not',
       'Referral Date', 'Cause of referral', 'Name of Referred Place',
       'Type of Referred Facility', 'Follow-up Date', 'Teleconsultation',
       'Remarks', 'referral', 'PEP'],
      dtype='object')

In [155]:
type(report.loc[2])

pandas.core.series.Series

In [68]:
report["Name of patient "]

0        Daw Khin Hla
1        Daw Khin Yee
2          Daw Mya Aye
3        Daw Nu Nu Yee
4      Daw Kyu Kyu San
            ...
903                NaN
904                NaN
905                NaN
906                NaN
907                NaN
Name: Name of patient , Length: 908, dtype: object

In [156]:
report["check"] = report["Name of patient "] !='NaN'
report.head()

,Sr.No,Fund,Implementing Organization Name,Health Post / Clinic,State,Township,Village Tract,Place,Type of place \n(Camp/Village/Ward),Name of Medical Person,...,Referral Date,Cause of referral,Name of Referred Place,Type of Referred Facility,Follow-up Date,Teleconsultation,Remarks,referral,PEP,check
0,1,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True
1,2,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True
2,3,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True
3,4,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True
4,5,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True

In [157]:
report["Referral Date"] = report["Referral Date"].fillna("Nothing")
report.head()

,Sr.No,Fund,Implementing Organization Name,Health Post / Clinic,State,Township,Village Tract,Place,Type of place \n(Camp/Village/Ward),Name of Medical Person,...,Referral Date,Cause of referral,Name of Referred Place,Type of Referred Facility,Follow-up Date,Teleconsultation,Remarks,referral,PEP,check
0,1,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,Nothing,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True
1,2,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,Nothing,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True
2,3,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,Nothing,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True
3,4,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,Nothing,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True
4,5,BHA,Shining Star,Mobile Clinic,Mandalay,Amarapura,NaN,Myit Too,Village,NaN,...,Nothing,NaN,NaN,NaN,NaN,No,NaN,NaN,#REF!,True

In [8]:
report.index

RangeIndex(start=0, stop=908, step=1)

In [9]:
report.columns

Index(['Sr.No', 'Fund', 'Implementing Organization Name',
       'Health Post / Clinic', 'State', 'Township', 'Village Tract', 'Place',
       'Type of place \n(Camp/Village/Ward)', 'Name of Medical Person',
       'Date of Consultation\n(mm/dd/yy)', 'Register No.', 'Register.Code',
       'New/\nFollow up', 'Name of patient ', 'Age_yr', 'Age_mth', 'Age_day',
       'Age_Group', 'Sex',
       'Address \n(if not the same with\nMoblile Clinic location)',
       'Father Name', 'Diagnosis', 'Sub_Category', 'Category',
       'Consultation Type', 'Treatment', 'eligible to receive PEP?',
       'Receive PEP within 72 hours', 'Disability', 'Refered or Not',
       'Referral Date', 'Cause of referral', 'Name of Referred Place',
       'Type of Referred Facility', 'Follow-up Date', 'Teleconsultation',
       'Remarks', 'referral', 'PEP', 'check'],
      dtype='object')

In [10]:
report.to_numpy()

array([[1, 'BHA', 'Shining Star', ..., nan, '#REF!', True],
       [2, 'BHA', 'Shining Star', ..., nan, '#REF!', True],
       [3, 'BHA', 'Shining Star', ..., nan, '#REF!', True],
       ...,
       [906, 'BHA', 'Shining Star', ..., nan, nan, True],
       [907, 'BHA', 'Shining Star', ..., nan, nan, True],
       [908, 'BHA', 'Shining Star', ..., nan, nan, True]],
      shape=(908, 41), dtype=object)

In [11]:
"State" in report.columns

True

In [12]:
3 in report.index

True

In [14]:
"check" in report.columns

True

In [15]:
report.shape

(908, 41)

In [158]:
report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 41 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Sr.No                                                    908 non-null    int64
 1   Fund                                                     908 non-null    object
 2   Implementing Organization Name                           908 non-null    object
 3   Health Post / Clinic                                     908 non-null    object
 4   State                                                    908 non-null    object
 5   Township                                                 820 non-null    object
 6   Village Tract                                            0 non-null      float64
 7   Place                                                    820 non-null    object
 8   Type of place
(Camp/Village/Ward)                       820 non-null    object
 9   Name of Medical Person                                   0 non-null      float64
 10  Date of Consultation
(mm/dd/yy)                          820 non-null    object
 11  Register No.                                             820 non-null    float64
 12  Register.Code                                            820 non-null    object
 13  New/
Follow up                                           907 non-null    object
 14  Name of patient                                          820 non-null    object
 15  Age_yr                                                   804 non-null    float64
 16  Age_mth                                                  24 non-null     float64
 17  Age_day                                                  4 non-null      float64
 18  Age_Group                                                908 non-null    object
 19  Sex                                                      820 non-null    object
 20  Address
(if not the same with
Moblile Clinic location)  443 non-null    object
 21  Father Name                                              803 non-null    object
 22  Diagnosis                                                818 non-null    object
 23  Sub_Category                                             778 non-null    object
 24  Category                                                 778 non-null    object
 25  Consultation Type                                        778 non-null    object
 26  Treatment                                                819 non-null    object
 27  eligible to receive PEP?                                 908 non-null    object
 28  Receive PEP within 72 hours                              908 non-null    object
 29  Disability                                               908 non-null    object
 30  Refered or Not                                           908 non-null    object
 31  Referral Date                                            908 non-null    object
 32  Cause of referral                                        0 non-null      float64
 33  Name of Referred Place                                   0 non-null      float64
 34  Type of Referred Facility                                0 non-null      float64
 35  Follow-up Date                                           0 non-null      float64
 36  Teleconsultation                                         726 non-null    object
 37  Remarks                                                  0 non-null      float64
 38  referral                                                 0 non-null      float64
 39  PEP                                                      820 non-null    object
 40  check                                                    908 non-null    bool
dtypes: bool(1), float64(12), int64(1), object(27)
memory usage: 284.8+ KB

In [159]:
report.isnull().sum()

Sr.No                                                          0
Fund                                                           0
Implementing Organization Name                                 0
Health Post / Clinic                                           0
State                                                          0
Township                                                      88
Village Tract                                                908
Place                                                         88
Type of place \n(Camp/Village/Ward)                           88
Name of Medical Person                                       908
Date of Consultation\n(mm/dd/yy)                              88
Register No.                                                  88
Register.Code                                                 88
New/\nFollow up                                                1
Name of patient                                               88
Age_yr                                                       104
Age_mth                                                      884
Age_day                                                      904
Age_Group                                                      0
Sex                                                           88
Address \n(if not the same with\nMoblile Clinic location)    465
Father Name                                                  105
Diagnosis                                                     90
Sub_Category                                                 130
Category                                                     130
Consultation Type                                            130
Treatment                                                     89
eligible to receive PEP?                                       0
Receive PEP within 72 hours                                    0
Disability                                                     0
Refered or Not                                                 0
Referral Date                                                  0
Cause of referral                                            908
Name of Referred Place                                       908
Type of Referred Facility                                    908
Follow-up Date                                               908
Teleconsultation                                             182
Remarks                                                      908
referral                                                     908
PEP                                                           88
check                                                          0
dtype: int64

In [160]:
report.describe()

,Sr.No,Village Tract,Name of Medical Person,Register No.,Age_yr,Age_mth,Age_day,Cause of referral,Name of Referred Place,Type of Referred Facility,Follow-up Date,Remarks,referral
count,908.00000,0.0,0.0,820.000000,804.000000,24.000000,4.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,454.50000,NaN,NaN,53.919512,50.247512,5.416667,15.500000,NaN,NaN,NaN,NaN,NaN,NaN
std,262.26132,NaN,NaN,32.901353,21.630882,2.842483,4.434712,NaN,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,1.000000,1.000000,1.000000,11.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,227.75000,NaN,NaN,26.000000,38.000000,3.000000,12.500000,NaN,NaN,NaN,NaN,NaN,NaN
50%,454.50000,NaN,NaN,52.000000,55.000000,6.000000,15.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,681.25000,NaN,NaN,79.000000,66.000000,8.000000,18.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,908.00000,NaN,NaN,132.000000,97.000000,10.000000,21.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
report.isnull().sum()

Sr.No                                                          0
Fund                                                           0
Implementing Organization Name                                 0
Health Post / Clinic                                           0
State                                                          0
Township                                                      88
Village Tract                                                908
Place                                                         88
Type of place \n(Camp/Village/Ward)                           88
Name of Medical Person                                       908
Date of Consultation\n(mm/dd/yy)                              88
Register No.                                                  88
Register.Code                                                 88
New/\nFollow up                                                1
Name of patient                                               88
Age_yr                                                       104
Age_mth                                                      884
Age_day                                                      904
Age_Group                                                      0
Sex                                                           88
Address \n(if not the same with\nMoblile Clinic location)    465
Father Name                                                  105
Diagnosis                                                     90
Sub_Category                                                 130
Category                                                     130
Consultation Type                                            130
Treatment                                                     89
eligible to receive PEP?                                       0
Receive PEP within 72 hours                                    0
Disability                                                     0
Refered or Not                                                 0
Referral Date                                                  0
Cause of referral                                            908
Name of Referred Place                                       908
Type of Referred Facility                                    908
Follow-up Date                                               908
Teleconsultation                                             182
Remarks                                                      908
referral                                                     908
PEP                                                           88
check                                                          0
dtype: int64

In [20]:
report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 41 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Sr.No                                                    908 non-null    int64
 1   Fund                                                     908 non-null    object
 2   Implementing Organization Name                           908 non-null    object
 3   Health Post / Clinic                                     908 non-null    object
 4   State                                                    908 non-null    object
 5   Township                                                 820 non-null    object
 6   Village Tract                                            0 non-null      float64
 7   Place                                                    820 non-null    object
 8   Type of place
(Camp/Village/Ward)                       820 non-null    object
 9   Name of Medical Person                                   0 non-null      float64
 10  Date of Consultation
(mm/dd/yy)                          820 non-null    object
 11  Register No.                                             820 non-null    float64
 12  Register.Code                                            820 non-null    object
 13  New/
Follow up                                           907 non-null    object
 14  Name of patient                                          820 non-null    object
 15  Age_yr                                                   804 non-null    float64
 16  Age_mth                                                  24 non-null     float64
 17  Age_day                                                  4 non-null      float64
 18  Age_Group                                                908 non-null    object
 19  Sex                                                      820 non-null    object
 20  Address
(if not the same with
Moblile Clinic location)  443 non-null    object
 21  Father Name                                              803 non-null    object
 22  Diagnosis                                                818 non-null    object
 23  Sub_Category                                             778 non-null    object
 24  Category                                                 778 non-null    object
 25  Consultation Type                                        778 non-null    object
 26  Treatment                                                819 non-null    object
 27  eligible to receive PEP?                                 908 non-null    object
 28  Receive PEP within 72 hours                              908 non-null    object
 29  Disability                                               908 non-null    object
 30  Refered or Not                                           908 non-null    object
 31  Referral Date                                            908 non-null    object
 32  Cause of referral                                        0 non-null      float64
 33  Name of Referred Place                                   0 non-null      float64
 34  Type of Referred Facility                                0 non-null      float64
 35  Follow-up Date                                           0 non-null      float64
 36  Teleconsultation                                         726 non-null    object
 37  Remarks                                                  0 non-null      float64
 38  referral                                                 0 non-null      float64
 39  PEP                                                      820 non-null    object
 40  check                                                    908 non-null    bool
dtypes: bool(1), float64(12), int64(1), object(27)
memory usage: 284.8+ KB

In [22]:
report.isnull()

,Sr.No,Fund,Implementing Organization Name,Health Post / Clinic,State,Township,Village Tract,Place,Type of place \n(Camp/Village/Ward),Name of Medical Person,...,Referral Date,Cause of referral,Name of Referred Place,Type of Referred Facility,Follow-up Date,Teleconsultation,Remarks,referral,PEP,check
0,False,False,False,False,False,False,True,False,False,True,...,False,True,True,True,True,False,True,True,False,False
1,False,False,False,False,False,False,True,False,False,True,...,False,True,True,True,True,False,True,True,False,False
2,False,False,False,False,False,False,True,False,False,True,...,False,True,True,True,True,False,True,True,False,False
3,False,False,False,False,False,False,True,False,False,True,...,False,True,True,True,True,False,True,True,False,False
4,False,False,False,False,False,False,True,False,False,True,...,False,True,True,True,True,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,False,False,False,False,False,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,False
904,False,False,False,False,False,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,False
905,False,False,False,False,False,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,False
906,False,False,False,False,False,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,False
907,False,False,False,False,False,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,False

In [24]:
report["Name of patient "]

0        Daw Khin Hla
1        Daw Khin Yee
2          Daw Mya Aye
3        Daw Nu Nu Yee
4      Daw Kyu Kyu San
            ...
903                NaN
904                NaN
905                NaN
906                NaN
907                NaN
Name: Name of patient , Length: 908, dtype: object

In [27]:
report.columns

Index(['Sr.No', 'Fund', 'Implementing Organization Name',
       'Health Post / Clinic', 'State', 'Township', 'Village Tract', 'Place',
       'Type of place \n(Camp/Village/Ward)', 'Name of Medical Person',
       'Date of Consultation\n(mm/dd/yy)', 'Register No.', 'Register.Code',
       'New/\nFollow up', 'Name of patient ', 'Age_yr', 'Age_mth', 'Age_day',
       'Age_Group', 'Sex',
       'Address \n(if not the same with\nMoblile Clinic location)',
       'Father Name', 'Diagnosis', 'Sub_Category', 'Category',
       'Consultation Type', 'Treatment', 'eligible to receive PEP?',
       'Receive PEP within 72 hours', 'Disability', 'Refered or Not',
       'Referral Date', 'Cause of referral', 'Name of Referred Place',
       'Type of Referred Facility', 'Follow-up Date', 'Teleconsultation',
       'Remarks', 'referral', 'PEP', 'check'],
      dtype='object')

In [162]:
columns_to_keep = ['Township', 'Village Tract', 'Place',
       'Type of place \n(Camp/Village/Ward)', 'Name of Medical Person',
       'Date of Consultation\n(mm/dd/yy)', 'Register No.', 'Register.Code',
       'New/\nFollow up', 'Name of patient ', 'Age_yr', 'Age_mth', 'Age_day',
       'Age_Group', 'Sex','Father Name', 'Diagnosis', 'Sub_Category', 'Category',
       'Consultation Type', 'Treatment']

In [163]:
report = report[columns_to_keep]

In [164]:
report.shape

(908, 21)

### 2 Method droping columns

In [165]:
report = report.drop(columns = ["Village Tract"])

In [166]:
report.columns

Index(['Township', 'Place', 'Type of place \n(Camp/Village/Ward)',
       'Name of Medical Person', 'Date of Consultation\n(mm/dd/yy)',
       'Register No.', 'Register.Code', 'New/\nFollow up', 'Name of patient ',
       'Age_yr', 'Age_mth', 'Age_day', 'Age_Group', 'Sex', 'Father Name',
       'Diagnosis', 'Sub_Category', 'Category', 'Consultation Type',
       'Treatment'],
      dtype='object')

In [167]:
column_to_drop=['New/\nFollow up','Father Name']

In [168]:
report = report.drop(columns = column_to_drop)

In [169]:
report.columns

Index(['Township', 'Place', 'Type of place \n(Camp/Village/Ward)',
       'Name of Medical Person', 'Date of Consultation\n(mm/dd/yy)',
       'Register No.', 'Register.Code', 'Name of patient ', 'Age_yr',
       'Age_mth', 'Age_day', 'Age_Group', 'Sex', 'Diagnosis', 'Sub_Category',
       'Category', 'Consultation Type', 'Treatment'],
      dtype='object')

In [170]:
report.shape

(908, 18)

### Rename Column Name

In [171]:
report.rename(columns = {"Type of place \n(Camp/Village/Ward)":"Type_Place"},inplace=True)

In [172]:
report.columns

Index(['Township', 'Place', 'Type_Place', 'Name of Medical Person',
       'Date of Consultation\n(mm/dd/yy)', 'Register No.', 'Register.Code',
       'Name of patient ', 'Age_yr', 'Age_mth', 'Age_day', 'Age_Group', 'Sex',
       'Diagnosis', 'Sub_Category', 'Category', 'Consultation Type',
       'Treatment'],
      dtype='object')

In [173]:
for i in report.columns:
    print(i.strip())

Township
Place
Type_Place
Name of Medical Person
Date of Consultation
(mm/dd/yy)
Register No.
Register.Code
Name of patient
Age_yr
Age_mth
Age_day
Age_Group
Sex
Diagnosis
Sub_Category
Category
Consultation Type
Treatment

### Checking Duplicate values

In [174]:
report.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
903     True
904     True
905     True
906     True
907     True
Length: 908, dtype: bool

In [175]:
report.duplicated().sum()

np.int64(87)

In [176]:
report.duplicated().value_counts()

False    821
True      87
Name: count, dtype: int64

In [177]:
report.drop_duplicates(inplace=True)

In [178]:
report.head()

,Township,Place,Type_Place,Name of Medical Person,Date of Consultation\n(mm/dd/yy),Register No.,Register.Code,Name of patient,Age_yr,Age_mth,Age_day,Age_Group,Sex,Diagnosis,Sub_Category,Category,Consultation Type,Treatment
0,Amarapura,Myit Too,Village,NaN,Jan - 15 - 2026,1.0,Shining Star-Mobile Clinic-BHA-PHC-1,Daw Khin Hla,80.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"Amlo5, MV, Betex"
1,Amarapura,Myit Too,Village,NaN,Jan - 15 - 2026,2.0,Shining Star-Mobile Clinic-BHA-PHC-2,Daw Khin Yee,89.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"IV25%+VitC, Amlo5, Para, MV, VitC"
2,Amarapura,Myit Too,Village,NaN,Jan - 15 - 2026,3.0,Shining Star-Mobile Clinic-BHA-PHC-3,Daw Mya Aye,63.0,NaN,NaN,50 yrs +,Female,Skin Allergy,Weakness,Other (non-communicable),Other,"IV B'ton, B'ton, Ranitadine, Ibu, Caladyl Lotion"
3,Amarapura,Myit Too,Village,NaN,Jan - 15 - 2026,4.0,Shining Star-Mobile Clinic-BHA-PHC-4,Daw Nu Nu Yee,73.0,NaN,NaN,50 yrs +,Female,Muscle Pain,Muscle Pain,Other (non-communicable),Other,"IV B12, Gabapentin, Betex, Ca+"
4,Amarapura,Myit Too,Village,NaN,Jan - 15 - 2026,5.0,Shining Star-Mobile Clinic-BHA-PHC-5,Daw Kyu Kyu San,50.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"IV Pantocid, Amlo5, Pantocid, Zinc, Air X"

In [124]:
report.isna().sum()

Township                              1
Place                                 1
Type_Place                            1
Name of Medical Person              821
Date of Consultation\n(mm/dd/yy)      1
Register No.                          1
Register.Code                         1
Name of patient                       1
Age_yr                               17
Age_mth                             797
Age_day                             817
Age_Group                             0
Sex                                   1
Diagnosis                             3
Sub_Category                         43
Category                             43
Consultation Type                    43
Treatment                             2
dtype: int64

In [179]:
report["Name of Medical Person"].fillna("Dr.Yar Zar",inplace=True)

C:\Users\NayMon\AppData\Local\Temp\ipykernel_4064\2501590093.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  report["Name of Medical Person"].fillna("Dr.Yar Zar",inplace=True)
C:\Users\NayMon\AppData\Local\Temp\ipykernel_4064\2501590093.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Dr.Yar Zar' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  report["Name of Medical Person"].fillna("Dr.Yar Zar",inplace=True)

In [180]:
report.head()

,Township,Place,Type_Place,Name of Medical Person,Date of Consultation\n(mm/dd/yy),Register No.,Register.Code,Name of patient,Age_yr,Age_mth,Age_day,Age_Group,Sex,Diagnosis,Sub_Category,Category,Consultation Type,Treatment
0,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,1.0,Shining Star-Mobile Clinic-BHA-PHC-1,Daw Khin Hla,80.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"Amlo5, MV, Betex"
1,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,2.0,Shining Star-Mobile Clinic-BHA-PHC-2,Daw Khin Yee,89.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"IV25%+VitC, Amlo5, Para, MV, VitC"
2,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,3.0,Shining Star-Mobile Clinic-BHA-PHC-3,Daw Mya Aye,63.0,NaN,NaN,50 yrs +,Female,Skin Allergy,Weakness,Other (non-communicable),Other,"IV B'ton, B'ton, Ranitadine, Ibu, Caladyl Lotion"
3,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,4.0,Shining Star-Mobile Clinic-BHA-PHC-4,Daw Nu Nu Yee,73.0,NaN,NaN,50 yrs +,Female,Muscle Pain,Muscle Pain,Other (non-communicable),Other,"IV B12, Gabapentin, Betex, Ca+"
4,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,5.0,Shining Star-Mobile Clinic-BHA-PHC-5,Daw Kyu Kyu San,50.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"IV Pantocid, Amlo5, Pantocid, Zinc, Air X"

In [129]:
report.isna().sum()

Township                              1
Place                                 1
Type_Place                            1
Name of Medical Person                0
Date of Consultation\n(mm/dd/yy)      1
Register No.                          1
Register.Code                         1
Name of patient                       1
Age_yr                               17
Age_mth                             797
Age_day                             817
Age_Group                             0
Sex                                   1
Diagnosis                             3
Sub_Category                         43
Category                             43
Consultation Type                    43
Treatment                             2
dtype: int64

In [181]:
report = report.dropna(subset=["Township"])

In [182]:
report.isna().sum()

Township                              0
Place                                 0
Type_Place                            0
Name of Medical Person                0
Date of Consultation\n(mm/dd/yy)      0
Register No.                          0
Register.Code                         0
Name of patient                       0
Age_yr                               16
Age_mth                             796
Age_day                             816
Age_Group                             0
Sex                                   0
Diagnosis                             2
Sub_Category                         42
Category                             42
Consultation Type                    42
Treatment                             1
dtype: int64

In [183]:
report[report["Treatment"].isna()]

,Township,Place,Type_Place,Name of Medical Person,Date of Consultation\n(mm/dd/yy),Register No.,Register.Code,Name of patient,Age_yr,Age_mth,Age_day,Age_Group,Sex,Diagnosis,Sub_Category,Category,Consultation Type,Treatment
527,PyiGyiTagon,Putsu Kyaung,Ward,Dr.Yar Zar,Feb - 11 - 2026,85.0,Shining Star-Mobile Clinic-BHA-PHC-85,B' Htay Htay Aung,NaN,NaN,13.0,<5 yrs,Female,Neonatal Care,Neonatal sepsis,Neonatal problem,Communicable disease,NaN

In [184]:
report["Treatment"].fillna("Mutil Vita",inplace =True)

C:\Users\NayMon\AppData\Local\Temp\ipykernel_4064\2628348276.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  report["Treatment"].fillna("Mutil Vita",inplace =True)

In [185]:
report.isna().sum()

Township                              0
Place                                 0
Type_Place                            0
Name of Medical Person                0
Date of Consultation\n(mm/dd/yy)      0
Register No.                          0
Register.Code                         0
Name of patient                       0
Age_yr                               16
Age_mth                             796
Age_day                             816
Age_Group                             0
Sex                                   0
Diagnosis                             2
Sub_Category                         42
Category                             42
Consultation Type                    42
Treatment                             0
dtype: int64

In [145]:
report.info()

<class 'pandas.core.frame.DataFrame'>
Index: 820 entries, 0 to 819
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Township                         820 non-null    object
 1   Place                            820 non-null    object
 2   Type_Place                       820 non-null    object
 3   Name of Medical Person           820 non-null    object
 4   Date of Consultation
(mm/dd/yy)  820 non-null    object
 5   Register No.                     820 non-null    float64
 6   Register.Code                    820 non-null    object
 7   Name of patient                  820 non-null    object
 8   Age_yr                           804 non-null    float64
 9   Age_mth                          24 non-null     float64
 10  Age_day                          4 non-null      float64
 11  Age_Group                        820 non-null    object
 12  Sex                              820 non-null    object
 13  Diagnosis                        818 non-null    object
 14  Sub_Category                     778 non-null    object
 15  Category                         778 non-null    object
 16  Consultation Type                778 non-null    object
 17  Treatment                        820 non-null    object
dtypes: float64(4), object(14)
memory usage: 154.0+ KB

In [188]:
report["Sub_Category"][2]

'Weakness'

In [189]:
report.head()

,Township,Place,Type_Place,Name of Medical Person,Date of Consultation\n(mm/dd/yy),Register No.,Register.Code,Name of patient,Age_yr,Age_mth,Age_day,Age_Group,Sex,Diagnosis,Sub_Category,Category,Consultation Type,Treatment
0,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,1.0,Shining Star-Mobile Clinic-BHA-PHC-1,Daw Khin Hla,80.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"Amlo5, MV, Betex"
1,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,2.0,Shining Star-Mobile Clinic-BHA-PHC-2,Daw Khin Yee,89.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"IV25%+VitC, Amlo5, Para, MV, VitC"
2,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,3.0,Shining Star-Mobile Clinic-BHA-PHC-3,Daw Mya Aye,63.0,NaN,NaN,50 yrs +,Female,Skin Allergy,Weakness,Other (non-communicable),Other,"IV B'ton, B'ton, Ranitadine, Ibu, Caladyl Lotion"
3,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,4.0,Shining Star-Mobile Clinic-BHA-PHC-4,Daw Nu Nu Yee,73.0,NaN,NaN,50 yrs +,Female,Muscle Pain,Muscle Pain,Other (non-communicable),Other,"IV B12, Gabapentin, Betex, Ca+"
4,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,5.0,Shining Star-Mobile Clinic-BHA-PHC-5,Daw Kyu Kyu San,50.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"IV Pantocid, Amlo5, Pantocid, Zinc, Air X"

In [191]:
report["Name of patient "].head(3)

0    Daw Khin Hla
1    Daw Khin Yee
2      Daw Mya Aye
Name: Name of patient , dtype: object

In [193]:
for i in report.columns:
    print(i.strip())

Township
Place
Type_Place
Name of Medical Person
Date of Consultation
(mm/dd/yy)
Register No.
Register.Code
Name of patient
Age_yr
Age_mth
Age_day
Age_Group
Sex
Diagnosis
Sub_Category
Category
Consultation Type
Treatment

In [194]:
report["Name of patient "].str.replace("Ko","U")

0           Daw Khin Hla
1           Daw Khin Yee
2             Daw Mya Aye
3           Daw Nu Nu Yee
4         Daw Kyu Kyu San
              ...
815    Ma May Yati Hlaing
816           U Htun Phay
817        Mg Aung Phyo
818          Daw Tin Aung
819          May Thu Htun
Name: Name of patient , Length: 820, dtype: object

In [195]:
report["Name of patient "].str.replace("Ma","Daw")

0             Daw Khin Hla
1             Daw Khin Yee
2               Daw Mya Aye
3             Daw Nu Nu Yee
4           Daw Kyu Kyu San
               ...
815    Daw Dawy Yati Hlaing
816             U Htun Phay
817          Mg Aung Phyo
818            Daw Tin Aung
819           Dawy Thu Htun
Name: Name of patient , Length: 820, dtype: object

In [198]:
%who

column_to_drop	 columns_to_keep	 dataframe_columns	 dataframe_hash	 dtypes_str	 get_dataframes	 getpass	 hashlib	 i
import_pandas_safely	 is_data_frame	 json	 pd	 report

In [199]:
report.to_csv("Clean_data.csv")

In [201]:
report_clean = pd.read_csv("Clean_data.csv")

In [202]:
report_clean.head()

,Unnamed: 0,Township,Place,Type_Place,Name of Medical Person,Date of Consultation\n(mm/dd/yy),Register No.,Register.Code,Name of patient,Age_yr,Age_mth,Age_day,Age_Group,Sex,Diagnosis,Sub_Category,Category,Consultation Type,Treatment
0,0,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,1.0,Shining Star-Mobile Clinic-BHA-PHC-1,Daw Khin Hla,80.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"Amlo5, MV, Betex"
1,1,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,2.0,Shining Star-Mobile Clinic-BHA-PHC-2,Daw Khin Yee,89.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"IV25%+VitC, Amlo5, Para, MV, VitC"
2,2,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,3.0,Shining Star-Mobile Clinic-BHA-PHC-3,Daw Mya Aye,63.0,NaN,NaN,50 yrs +,Female,Skin Allergy,Weakness,Other (non-communicable),Other,"IV B'ton, B'ton, Ranitadine, Ibu, Caladyl Lotion"
3,3,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,4.0,Shining Star-Mobile Clinic-BHA-PHC-4,Daw Nu Nu Yee,73.0,NaN,NaN,50 yrs +,Female,Muscle Pain,Muscle Pain,Other (non-communicable),Other,"IV B12, Gabapentin, Betex, Ca+"
4,4,Amarapura,Myit Too,Village,Dr.Yar Zar,Jan - 15 - 2026,5.0,Shining Star-Mobile Clinic-BHA-PHC-5,Daw Kyu Kyu San,50.0,NaN,NaN,50 yrs +,Female,HT,Hypertension,Chronic medical disease,Non-communicable disease,"IV Pantocid, Amlo5, Pantocid, Zinc, Air X"